apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-access-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
